version: "3.3"

services:
  nginx-healthcheck:
    container_name: nginx-healthcheck
    restart: always
    image: nginx:1.23.1
    volumes:
      - ./nginx/conf/:/etc/nginx/:ro
      - ./nginx/cert/:/ssl/:ro
      - ./nginx/statics/:/staticfiles/:ro
    ports:
      - 443:443
    networks:
      - healthcheck-network
    logging:
      driver: "json-file"
      options:
        max-size: 5m

  backend-healthcheck:
    container_name: backend-healthcheck
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    restart: always
    environment:
      PLATFORM: "production"
      SWAGGER_URL: "https://healthcheck.alinance.ir"
      API_HOST: "healthcheck.alinance.ir"
    command: bash -c " ./manage.py makemigrations && ./manage.py migrate && ./manage.py generate-config && uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --workers 2"
    networks:
      - healthcheck-network
    volumes:
      - ./db:/app/db

  crontab-healthcheck:
    container_name: crontab-healthcheck
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    restart: always
    environment:
      PLATFORM: "production"
      SWAGGER_URL: "https://healthcheck.alinance.ir"
      API_HOST: "healthcheck.alinance.ir"
    command: bash -c "./manage.py worker"
    networks:
      - healthcheck-network
    volumes:
      - ./db:/app/db

networks:
  healthcheck-network:
    external: True
