version: "3.3"

services:
  redis-backend:
    container_name: redis-backend
    restart: always
    image: redis:6.2.7
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - redis-backend-data:/data
      - ./server-conf/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - backend-network

  postgres-backend:
    container_name: postgres-backend
    restart: always
    image: postgres:14.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres-backend-data:/var/lib/postgresql/data
    networks:
      - backend-network

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.23.1
    volumes:
      - ./server-conf/nginx/conf/:/etc/nginx/:ro
    ports:
      - 80:80
    networks:
      - backend-network

volumes:
  redis-backend-data:
    external: True
  postgres-backend-data:
    external: True

networks:
  backend-network:
    external: True
