version: "3.3"

services:
  backend-web:
    container_name: backend-web
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      PLATFORM: "production"
      SWAGGER_URL: "https://healthcheck.abantechnical.ir"
      API_HOST: "healthcheck.abantechnical.ir"
      BACKEND_REDIS_HOST: "redis-backend"
      BACKEND_POSTGRES_HOST: "postgres-backend"
      BACKEND_POSTGRES_NAME: "postgres"
      BACKEND_POSTGRES_USERNAME: "postgres"
      BACKEND_POSTGRES_PASSWORD: "postgres"
    command: bash -c "./manage.py migrate && uvicorn backend.asgi:application --host 0.0.0.0 --port 8080 --workers 2"
    networks:
      - backend-network
    logging:
      driver: "json-file"
      options:
        max-size: 5m

networks:
  backend-network:
    external: True
