from os import getenv

PLATFORM = getenv("PLATFORM", "local")
API_HOST = getenv("API_HOST", "127.0.0.1")
SWAGGER_URL = getenv("SWAGGER_URL", "http://127.0.0.1:8000")
BOT_TOKEN = getenv("BOT_TOKEN", "")
PROJECT_SECRET_KEY = getenv(
    "SECRET_KEY", "django-insecure-w009)3tg7g**m=)v3%op^)6m3wf0a#hw0-7dff$%-_l*C%68SE"
)

BACKEND_REDIS_HOST = getenv("BACKEND_REDIS_HOST", "127.0.0.1")
BACKEND_REDIS_PORT = getenv("BACKEND_REDIS_PORT", "6379")

BACKEND_POSTGRES_HOST = getenv("BACKEND_POSTGRES_HOST", "127.0.0.1")
BACKEND_POSTGRES_PORT = getenv("BACKEND_POSTGRES_PORT", "5432")
BACKEND_POSTGRES_NAME = getenv("BACKEND_POSTGRES_NAME", "postgres")
BACKEND_POSTGRES_USERNAME = getenv("BACKEND_POSTGRES_USERNAME", "postgres")
BACKEND_POSTGRES_PASSWORD = getenv("BACKEND_POSTGRES_PASSWORD", "postgres")

REDIS_DEFAULT = "0"
REDIS_RATELIMIT = "1"
REDIS_CELERY_BROKER = "2"
REDIS_CELERY_BACKEND = "3"
REDIS_CACHE_LOCK = "4"
