# Generated by Django 3.2.18 on 2023-04-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20230315_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='body',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='headers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='query_params',
            field=models.JSONField(null=True),
        ),
    ]
