# Generated by Django 3.2.18 on 2023-04-03 11:50

import backend.customs.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20230403_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callresult',
            name='timestamp',
            field=models.IntegerField(default=backend.customs.generators.current_int_timestamp),
        ),
    ]
